"""Politique locale de sécurité des actions JARVIS."""

SAFE_ACTION = "SAFE_ACTION"
CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
BLOCKED_ACTION = "BLOCKED_ACTION"

_POLICY = {
    "GREETINGS": SAFE_ACTION,
    "GET_TIME": SAFE_ACTION,
    "OPEN_BROWSER": SAFE_ACTION,
    "OPEN_SPOTIFY": SAFE_ACTION,
    "PLAY_MUSIC": SAFE_ACTION,
    "OPEN_TERMINAL": SAFE_ACTION,
    "OPEN_VSCODE": SAFE_ACTION,
    "OPEN_PROJECT": SAFE_ACTION,
    "LIST_PROJECTS": SAFE_ACTION,
    "OPEN_FIREFOX": SAFE_ACTION,
    "OPEN_SITE": SAFE_ACTION,
    "OPEN_WEBSITE": SAFE_ACTION,
    "OPEN_FOLDER": SAFE_ACTION,
    "LIST_APPLICATIONS": SAFE_ACTION, "WINDOW_LIST": SAFE_ACTION, "WINDOW_FOCUS": CONFIRMATION_REQUIRED,
    "WINDOW_MINIMIZE": CONFIRMATION_REQUIRED, "WINDOW_MAXIMIZE": SAFE_ACTION, "WINDOW_CLOSE": CONFIRMATION_REQUIRED,
    "OPEN_APPLICATION": SAFE_ACTION,
    "SEARCH_MUSIC": SAFE_ACTION,
    "OPEN_URL": SAFE_ACTION,
    "SEARCH_WEB": SAFE_ACTION,
    "SEARCH_WIKIPEDIA": SAFE_ACTION,
    "PAUSE_MUSIC": SAFE_ACTION,
    "RESUME_MUSIC": SAFE_ACTION,
    "NEXT_TRACK": SAFE_ACTION,
    "PREVIOUS_TRACK": SAFE_ACTION,
    "SCREENSHOT": SAFE_ACTION,
    "OPEN_FOLDER": SAFE_ACTION,
    "FILE_OPEN": SAFE_ACTION,
    "FILE_CREATE": SAFE_ACTION,
    "FILE_COPY": SAFE_ACTION,
    "FILE_MOVE": SAFE_ACTION,
    "FILE_DELETE": CONFIRMATION_REQUIRED,
    "VOLUME_UP": SAFE_ACTION,
    "VOLUME_DOWN": SAFE_ACTION,
    "VOLUME_MUTE": SAFE_ACTION,
    "MEDIA_PLAY": SAFE_ACTION,
    "MEDIA_PAUSE": SAFE_ACTION,
    "MEDIA_NEXT": SAFE_ACTION,
    "MEDIA_PREVIOUS": SAFE_ACTION,
    "WIFI_STATUS": SAFE_ACTION, "WIFI_ENABLE": SAFE_ACTION, "WIFI_DISABLE": SAFE_ACTION, "WIFI_OPEN_SETTINGS": SAFE_ACTION,
    "BLUETOOTH_STATUS": SAFE_ACTION, "BLUETOOTH_ENABLE": SAFE_ACTION, "BLUETOOTH_DISABLE": SAFE_ACTION, "BLUETOOTH_OPEN_SETTINGS": SAFE_ACTION,
    "VOLUME_STATUS": SAFE_ACTION, "VOLUME_SET": SAFE_ACTION,
    "VOLUME_UNMUTE": SAFE_ACTION, "MEDIA_STATUS": SAFE_ACTION, "PC_STATUS": SAFE_ACTION, "CPU_STATUS": SAFE_ACTION, "RAM_STATUS": SAFE_ACTION, "GPU_STATUS": SAFE_ACTION, "APPLICATION_LIST": SAFE_ACTION,
    "BRIGHTNESS_UP": SAFE_ACTION, "BRIGHTNESS_DOWN": SAFE_ACTION, "BRIGHTNESS_STATUS": SAFE_ACTION, "BRIGHTNESS_SET": SAFE_ACTION,
    "CLOSE_APPLICATION": CONFIRMATION_REQUIRED,
    "RUN_COMMAND": CONFIRMATION_REQUIRED,
    "DELETE_FILE": BLOCKED_ACTION,
    "FORMAT_DISK": BLOCKED_ACTION,
    "ROOT_COMMAND": BLOCKED_ACTION,
}


def classify_action(action):
    return _POLICY.get(action, BLOCKED_ACTION)


def detect_sensitive_request(message):
    text = str(message or "").casefold()
    if any(word in text for word in ("supprime", "efface", "formatte")):
        return "FILE_DELETE" if "fichier" in text else "DELETE_FILE"
    if any(word in text for word in ("ferme l application", "fermer l application", "ferme cette application")):
        return "CLOSE_APPLICATION"
    return None
